CREATE TABLE [dbo].[Aircrafts] (
    [AircraftId]              UNIQUEIDENTIFIER NOT NULL,
    [ManufacturerName]        NVARCHAR (100)   NULL,
    [AircraftModel]           NVARCHAR (50)    NULL,
    [Immatriculation]         NVARCHAR (15)    NOT NULL,
    [CompetitionSign]         NVARCHAR (5)     NULL,
    [NrOfSeats]               INT              NULL,
    [DaecIndex]               INT              NULL,
    [Comment]                 NVARCHAR (250)   NULL,
    [AircraftType]            INT              CONSTRAINT [DF__Aircrafts__Aircr__33D4B598] DEFAULT ((0)) NOT NULL,
    [IsTowingOrWinchRequired] BIT              CONSTRAINT [DF__Aircrafts__IsTow__34C8D9D1] DEFAULT ((0)) NOT NULL,
    [IsTowingstartAllowed]    BIT              CONSTRAINT [DF__Aircrafts__IsTow__35BCFE0A] DEFAULT ((0)) NOT NULL,
    [IsWinchstartAllowed]     BIT              CONSTRAINT [DF__Aircrafts__IsWin__36B12243] DEFAULT ((0)) NOT NULL,
    [IsTowingAircraft]        BIT              CONSTRAINT [DF__Aircrafts__IsTow__37A5467C] DEFAULT ((0)) NOT NULL,
    [AircraftOwnerClubId]     UNIQUEIDENTIFIER NULL,
    [AircraftOwnerPersonId]   UNIQUEIDENTIFIER NULL,
    [FLARMId]                 NVARCHAR (50)    NULL,
    [AircraftSerialNumber]    NVARCHAR (20)    NULL,
    [YearOfManufacture]       DATETIME2 (7)    NULL,
    [NoiseClass]              NVARCHAR (1)     NULL,
    [NoiseLevel]              NUMERIC (18, 1)  NULL,
    [MTOM]                    INT              NULL,
    [FlightDurationPrecision] INT              CONSTRAINT [DF_Aircrafts_FlightDurationPrecision] DEFAULT ((1)) NOT NULL,
    [SpotLink]                NVARCHAR (250)   NULL,
    [IsFastEntryRecord]       BIT              CONSTRAINT [DF__Aircrafts__IsFas__38996AB5] DEFAULT ((1)) NOT NULL,
    [CreatedOn]               DATETIME2 (7)    NOT NULL,
    [CreatedByUserId]         UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]              DATETIME2 (7)    NULL,
    [ModifiedByUserId]        UNIQUEIDENTIFIER NULL,
    [DeletedOn]               DATETIME2 (7)    NULL,
    [DeletedByUserId]         UNIQUEIDENTIFIER NULL,
    [RecordState]             INT              NULL,
    [OwnerId]                 UNIQUEIDENTIFIER NOT NULL,
    [OwnershipType]           INT              NOT NULL,
    [IsDeleted]               BIT              CONSTRAINT [DF__Aircrafts__IsDel__398D8EEE] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Aircrafts] PRIMARY KEY CLUSTERED ([AircraftId] ASC),
    CONSTRAINT [FK_Aircrafts_AircraftTypes] FOREIGN KEY ([AircraftType]) REFERENCES [dbo].[AircraftTypes] ([AircraftTypeId]),
    CONSTRAINT [FK_Aircrafts_OwnerClub] FOREIGN KEY ([AircraftOwnerClubId]) REFERENCES [dbo].[Clubs] ([ClubId]),
    CONSTRAINT [FK_Aircrafts_OwnerPerson] FOREIGN KEY ([AircraftOwnerPersonId]) REFERENCES [dbo].[Persons] ([PersonId]),
    CONSTRAINT [UNIQUE_Aircrafts_Immatriculation] UNIQUE NONCLUSTERED ([Immatriculation] ASC, [DeletedOn] ASC)
);

