CREATE TABLE [dbo].[AircraftReservations] (
    [AircraftReservationId] UNIQUEIDENTIFIER NOT NULL,
    [Start]                 DATETIME2 (7)    NOT NULL,
    [End]                   DATETIME2 (7)    NOT NULL,
    [IsAllDayReservation]   BIT              NOT NULL,
    [AircraftId]            UNIQUEIDENTIFIER NOT NULL,
    [LocationId]            UNIQUEIDENTIFIER NOT NULL,
    [PilotPersonId]         UNIQUEIDENTIFIER NOT NULL,
    [InstructorPersonId]    UNIQUEIDENTIFIER NULL,
    [ReservationTypeId]     INT              NOT NULL,
    [Remarks]               NVARCHAR (MAX)   NULL,
    [ClubId]                UNIQUEIDENTIFIER NOT NULL,
    [CreatedOn]             DATETIME2 (7)    NOT NULL,
    [CreatedByUserId]       UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]            DATETIME2 (7)    NULL,
    [ModifiedByUserId]      UNIQUEIDENTIFIER NULL,
    [DeletedOn]             DATETIME2 (7)    NULL,
    [DeletedByUserId]       UNIQUEIDENTIFIER NULL,
    [RecordState]           INT              NULL,
    [OwnerId]               UNIQUEIDENTIFIER NOT NULL,
    [OwnershipType]         INT              NOT NULL,
    [IsDeleted]             BIT              NOT NULL,
    CONSTRAINT [PK_dbo.AircraftReservations] PRIMARY KEY CLUSTERED ([AircraftReservationId] ASC),
    CONSTRAINT [FK_dbo.AircraftReservations_dbo.AircraftReservationTypes_ReservationTypeId] FOREIGN KEY ([ReservationTypeId]) REFERENCES [dbo].[AircraftReservationTypes] ([AircraftReservationTypeId]),
    CONSTRAINT [FK_dbo.AircraftReservations_dbo.Aircrafts_AircraftId] FOREIGN KEY ([AircraftId]) REFERENCES [dbo].[Aircrafts] ([AircraftId]),
    CONSTRAINT [FK_dbo.AircraftReservations_dbo.Clubs_ClubId] FOREIGN KEY ([ClubId]) REFERENCES [dbo].[Clubs] ([ClubId]),
    CONSTRAINT [FK_dbo.AircraftReservations_dbo.Locations_LocationId] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Locations] ([LocationId]),
    CONSTRAINT [FK_dbo.AircraftReservations_dbo.Persons_InstructorPersonId] FOREIGN KEY ([InstructorPersonId]) REFERENCES [dbo].[Persons] ([PersonId]),
    CONSTRAINT [FK_dbo.AircraftReservations_dbo.Persons_PilotPersonId] FOREIGN KEY ([PilotPersonId]) REFERENCES [dbo].[Persons] ([PersonId])
);

