CREATE TABLE [dbo].[Clubs] (
    [ClubId]                        UNIQUEIDENTIFIER NOT NULL,
    [Clubname]                      NVARCHAR (100)   NOT NULL,
    [ClubKey]                       NVARCHAR (10)    NOT NULL,
    [Address]                       NVARCHAR (100)   NULL,
    [Zip]                           NVARCHAR (10)    NULL,
    [City]                          NVARCHAR (100)   NULL,
    [CountryId]                     UNIQUEIDENTIFIER NOT NULL,
    [Phone]                         NVARCHAR (30)    NULL,
    [FaxNumber]                     NVARCHAR (30)    NULL,
    [Email]                         NVARCHAR (256)   NULL,
    [WebPage]                       NVARCHAR (100)   NULL,
    [Contact]                       NVARCHAR (100)   NULL,
    [HomebaseId]                    UNIQUEIDENTIFIER NULL,
    [DefaultStartType]              INT              NULL,
    [DefaultGliderFlightTypeId]     UNIQUEIDENTIFIER NULL,
    [DefaultTowFlightTypeId]        UNIQUEIDENTIFIER NULL,
    [DefaultMotorFlightTypeId]      UNIQUEIDENTIFIER NULL,
    [LastPersonSynchronisationOn]   DATETIME2 (7)    NULL,
    [LastInvoiceExportOn]           DATETIME2 (7)    NULL,
    [CreatedOn]                     DATETIME2 (7)    NOT NULL,
    [CreatedByUserId]               UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]                    DATETIME2 (7)    NULL,
    [ModifiedByUserId]              UNIQUEIDENTIFIER NULL,
    [DeletedOn]                     DATETIME2 (7)    NULL,
    [DeletedByUserId]               UNIQUEIDENTIFIER NULL,
    [RecordState]                   INT              NULL,
    [OwnerId]                       UNIQUEIDENTIFIER NOT NULL,
    [OwnershipType]                 INT              NOT NULL,
    [IsDeleted]                     BIT              CONSTRAINT [DF__Clubs__IsDeleted__108B795B] DEFAULT ((0)) NOT NULL,
    [SendAircraftStatisticReportTo] NVARCHAR (250)   NULL,
    [SendPlanningDayInfoMailTo]     NVARCHAR (250)   NULL,
    [SendInvoiceReportsTo]          NVARCHAR (250)   NULL,
    [ClubStateId]                   INT              NOT NULL,
    CONSTRAINT [PK_Clubs] PRIMARY KEY CLUSTERED ([ClubId] ASC),
    CONSTRAINT [FK_Club_Homebase] FOREIGN KEY ([HomebaseId]) REFERENCES [dbo].[Locations] ([LocationId]),
    CONSTRAINT [FK_Clubs_ClubStates] FOREIGN KEY ([ClubStateId]) REFERENCES [dbo].[ClubStates] ([ClubStateId]),
    CONSTRAINT [FK_Clubs_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([CountryId]),
    CONSTRAINT [FK_Clubs_DefaultGliderFlightTypeId] FOREIGN KEY ([DefaultGliderFlightTypeId]) REFERENCES [dbo].[FlightTypes] ([FlightTypeId]),
    CONSTRAINT [FK_Clubs_DefaultMotorFlightTypeId] FOREIGN KEY ([DefaultMotorFlightTypeId]) REFERENCES [dbo].[FlightTypes] ([FlightTypeId]),
    CONSTRAINT [FK_Clubs_DefaultStartType] FOREIGN KEY ([DefaultStartType]) REFERENCES [dbo].[StartTypes] ([StartTypeId]),
    CONSTRAINT [FK_Clubs_DefaultTowFlightTypeId] FOREIGN KEY ([DefaultTowFlightTypeId]) REFERENCES [dbo].[FlightTypes] ([FlightTypeId]),
    CONSTRAINT [UNIQUE_Club_ClubKey] UNIQUE NONCLUSTERED ([ClubKey] ASC, [DeletedOn] ASC),
    CONSTRAINT [UNIQUE_Club_Clubname] UNIQUE NONCLUSTERED ([Clubname] ASC, [DeletedOn] ASC)
);

