CREATE TABLE [dbo].[Flights] (
    [FlightId]                             UNIQUEIDENTIFIER NOT NULL,
    [AircraftId]                           UNIQUEIDENTIFIER NOT NULL,
    [StartPosition]                        INT              NULL,
    [StartDateTime]                        DATETIME2 (7)    NULL,
    [LdgDateTime]                          DATETIME2 (7)    NULL,
    [EngineTime]                           DATETIME2 (7)    NULL,
    [BlockStartDateTime]                   DATETIME2 (7)    NULL,
    [BlockEndDateTime]                     DATETIME2 (7)    NULL,
    [StartLocationId]                      UNIQUEIDENTIFIER NULL,
    [LdgLocationId]                        UNIQUEIDENTIFIER NULL,
    [StartRunway]                          NVARCHAR (5)     NULL,
    [LdgRunway]                            NVARCHAR (5)     NULL,
    [OutboundRoute]                        NVARCHAR (50)    NULL,
    [InboundRoute]                         NVARCHAR (50)    NULL,
    [FlightTypeId]                         UNIQUEIDENTIFIER NULL,
    [IsSoloFlight]                         BIT              CONSTRAINT [DF__Flights__IsSoloF__5CD6CB2B] DEFAULT ((0)) NOT NULL,
    [StartType]                            INT              NULL,
    [TowFlightId]                          UNIQUEIDENTIFIER NULL,
    [NrOfLdgs]                             INT              NULL,
    [FlightState]                          INT              NOT NULL,
    [FlightAircraftType]                   INT              NOT NULL,
    [Comment]                              NVARCHAR (MAX)   NULL,
    [IncidentComment]                      NVARCHAR (MAX)   NULL,
    [FlightCostBalanceType]                INT              CONSTRAINT [DF__Flights__FlightC__5DCAEF64] DEFAULT ((1)) NULL,
    [InvoicedOn]                           DATETIME2 (7)    NULL,
    [InvoiceNumber]                        NVARCHAR (100)   NULL,
    [DeliveryNumber]                       NVARCHAR (100)   NULL,
    [InvoicePaidOn]                        DATETIME2 (7)    NULL,
    [CreatedOn]                            DATETIME2 (7)    NOT NULL,
    [CreatedByUserId]                      UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]                           DATETIME2 (7)    NULL,
    [ModifiedByUserId]                     UNIQUEIDENTIFIER NULL,
    [DeletedOn]                            DATETIME2 (7)    NULL,
    [DeletedByUserId]                      UNIQUEIDENTIFIER NULL,
    [RecordState]                          INT              NULL,
    [OwnerId]                              UNIQUEIDENTIFIER NOT NULL,
    [OwnershipType]                        INT              NOT NULL,
    [IsDeleted]                            BIT              CONSTRAINT [DF__Flights__IsDelet__5EBF139D] DEFAULT ((0)) NOT NULL,
    [ValidatedOn]                          DATETIME2 (7)    NULL,
    [CouponNumber]                         NVARCHAR (20)    NULL,
    [EngineStartOperatingCounterInMinutes] NUMERIC (18, 3)  NULL,
    [EngineEndOperatingCounterInMinutes]   NUMERIC (18, 3)  NULL,
    CONSTRAINT [PK_Flights] PRIMARY KEY CLUSTERED ([FlightId] ASC),
    CONSTRAINT [FK_Flights_Aircraft] FOREIGN KEY ([AircraftId]) REFERENCES [dbo].[Aircrafts] ([AircraftId]),
    CONSTRAINT [FK_Flights_FlightCostBalanceTypes] FOREIGN KEY ([FlightCostBalanceType]) REFERENCES [dbo].[FlightCostBalanceTypes] ([FlightCostBalanceTypeId]),
    CONSTRAINT [FK_Flights_Flights] FOREIGN KEY ([TowFlightId]) REFERENCES [dbo].[Flights] ([FlightId]),
    CONSTRAINT [FK_Flights_FlightStates] FOREIGN KEY ([FlightState]) REFERENCES [dbo].[FlightStates] ([FlightStateId]),
    CONSTRAINT [FK_Flights_FlightTypes] FOREIGN KEY ([FlightTypeId]) REFERENCES [dbo].[FlightTypes] ([FlightTypeId]),
    CONSTRAINT [FK_Flights_Ldg_Locations] FOREIGN KEY ([LdgLocationId]) REFERENCES [dbo].[Locations] ([LocationId]),
    CONSTRAINT [FK_Flights_Start_Locations] FOREIGN KEY ([StartLocationId]) REFERENCES [dbo].[Locations] ([LocationId]),
    CONSTRAINT [FK_Flights_StartTypes] FOREIGN KEY ([StartType]) REFERENCES [dbo].[StartTypes] ([StartTypeId])
);

