CREATE TABLE [dbo].[FlightTypes] (
    [FlightTypeId]                      UNIQUEIDENTIFIER NOT NULL,
    [ClubId]                            UNIQUEIDENTIFIER NOT NULL,
    [FlightTypeName]                    NVARCHAR (100)   NOT NULL,
    [FlightCode]                        NVARCHAR (30)    NULL,
    [InstructorRequired]                BIT              NOT NULL,
    [ObserverPilotOrInstructorRequired] BIT              NOT NULL,
    [IsCheckFlight]                     BIT              NOT NULL,
    [IsPassengerFlight]                 BIT              NOT NULL,
    [IsSoloFlight]                      BIT              DEFAULT ((0)) NOT NULL,
    [IsForGliderFlights]                BIT              DEFAULT ((1)) NOT NULL,
    [IsForTowFlights]                   BIT              DEFAULT ((0)) NOT NULL,
    [IsForMotorFlights]                 BIT              DEFAULT ((0)) NOT NULL,
    [IsFlightCostBalanceSelectable]     BIT              DEFAULT ((1)) NOT NULL,
    [CreatedOn]                         DATETIME2 (7)    NOT NULL,
    [CreatedByUserId]                   UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]                        DATETIME2 (7)    NULL,
    [ModifiedByUserId]                  UNIQUEIDENTIFIER NULL,
    [DeletedOn]                         DATETIME2 (7)    NULL,
    [DeletedByUserId]                   UNIQUEIDENTIFIER NULL,
    [RecordState]                       INT              NULL,
    [OwnerId]                           UNIQUEIDENTIFIER NOT NULL,
    [OwnershipType]                     INT              NOT NULL,
    [IsDeleted]                         BIT              DEFAULT ((0)) NOT NULL,
    [IsCouponNumberRequired]            BIT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_FlightTypes] PRIMARY KEY CLUSTERED ([FlightTypeId] ASC),
    CONSTRAINT [FK_FlightTypes_Club] FOREIGN KEY ([ClubId]) REFERENCES [dbo].[Clubs] ([ClubId]),
    CONSTRAINT [UNIQUE_FlightTypes_FlightTypeName] UNIQUE NONCLUSTERED ([FlightTypeName] ASC, [ClubId] ASC, [DeletedOn] ASC)
);

