CREATE TABLE [dbo].[PersonClub] (
    [PersonId]                                UNIQUEIDENTIFIER NOT NULL,
    [ClubId]                                  UNIQUEIDENTIFIER NOT NULL,
    [MemberNumber]                            NVARCHAR (20)    NULL,
    [MemberKey]                               NVARCHAR (40)    NULL,
    [IsMotorPilot]                            BIT              DEFAULT ((0)) NOT NULL,
    [IsTowPilot]                              BIT              DEFAULT ((0)) NOT NULL,
    [IsGliderInstructor]                      BIT              DEFAULT ((0)) NOT NULL,
    [IsGliderPilot]                           BIT              DEFAULT ((0)) NOT NULL,
    [IsGliderTrainee]                         BIT              DEFAULT ((0)) NOT NULL,
    [IsPassenger]                             BIT              NOT NULL,
    [IsWinchOperator]                         BIT              DEFAULT ((0)) NOT NULL,
    [CreatedOn]                               DATETIME2 (7)    NOT NULL,
    [CreatedByUserId]                         UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]                              DATETIME2 (7)    NULL,
    [ModifiedByUserId]                        UNIQUEIDENTIFIER NULL,
    [DeletedOn]                               DATETIME2 (7)    NULL,
    [DeletedByUserId]                         UNIQUEIDENTIFIER NULL,
    [RecordState]                             INT              NULL,
    [OwnerId]                                 UNIQUEIDENTIFIER NOT NULL,
    [OwnershipType]                           INT              NOT NULL,
    [IsDeleted]                               BIT              DEFAULT ((0)) NOT NULL,
    [ReceiveFlightReports]                    BIT              DEFAULT ((1)) NOT NULL,
    [ReceiveAircraftReservationNotifications] BIT              DEFAULT ((1)) NOT NULL,
    [ReceivePlanningDayRoleReminder]          BIT              DEFAULT ((1)) NOT NULL,
    [MemberStateId]                           UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK_PersonClub] PRIMARY KEY CLUSTERED ([PersonId] ASC, [ClubId] ASC),
    CONSTRAINT [FK_PersonClub_Club] FOREIGN KEY ([ClubId]) REFERENCES [dbo].[Clubs] ([ClubId]),
    CONSTRAINT [FK_PersonClub_MemberState] FOREIGN KEY ([MemberStateId]) REFERENCES [dbo].[MemberStates] ([MemberStateId]),
    CONSTRAINT [FK_PersonClub_Person] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[Persons] ([PersonId]),
    CONSTRAINT [UNIQUE_PersonClub_PersonId_ClubId_MemberKey] UNIQUE NONCLUSTERED ([PersonId] ASC, [ClubId] ASC, [MemberKey] ASC, [DeletedOn] ASC),
    CONSTRAINT [UNIQUE_PersonClub_PersonId_ClubId_MemberNumber] UNIQUE NONCLUSTERED ([PersonId] ASC, [ClubId] ASC, [MemberNumber] ASC, [DeletedOn] ASC)
);

