CREATE TABLE [dbo].[Persons] (
    [PersonId]                             UNIQUEIDENTIFIER NOT NULL,
    [Lastname]                             NVARCHAR (100)   NOT NULL,
    [Firstname]                            NVARCHAR (100)   NOT NULL,
    [Midname]                              NVARCHAR (100)   NULL,
    [CompanyName]                          NVARCHAR (100)   NULL,
    [AddressLine1]                         NVARCHAR (200)   NULL,
    [AddressLine2]                         NVARCHAR (200)   NULL,
    [Zip]                                  NVARCHAR (10)    NULL,
    [City]                                 NVARCHAR (100)   NULL,
    [Region]                               NVARCHAR (100)   NULL,
    [CountryId]                            UNIQUEIDENTIFIER NULL,
    [PrivatePhone]                         NVARCHAR (30)    NULL,
    [MobilePhone]                          NVARCHAR (30)    NULL,
    [BusinessPhone]                        NVARCHAR (30)    NULL,
    [FaxNumber]                            NVARCHAR (30)    NULL,
    [EmailPrivate]                         NVARCHAR (256)   NULL,
    [EmailBusiness]                        NVARCHAR (256)   NULL,
    [PreferMailToBusinessMail]             BIT              CONSTRAINT [DF__Persons__PreferM__4CA06362] DEFAULT ((0)) NOT NULL,
    [Birthday]                             DATE             NULL,
    [HasMotorPilotLicence]                 BIT              CONSTRAINT [DF__Persons__HasMoto__4D94879B] DEFAULT ((0)) NOT NULL,
    [HasTowPilotLicence]                   BIT              CONSTRAINT [DF__Persons__HasTowP__4E88ABD4] DEFAULT ((0)) NOT NULL,
    [HasGliderInstructorLicence]           BIT              CONSTRAINT [DF__Persons__HasGlid__4F7CD00D] DEFAULT ((0)) NOT NULL,
    [HasGliderPilotLicence]                BIT              CONSTRAINT [DF__Persons__HasGlid__5070F446] DEFAULT ((0)) NOT NULL,
    [HasGliderTraineeLicence]              BIT              CONSTRAINT [DF__Persons__HasGlid__5165187F] DEFAULT ((0)) NOT NULL,
    [HasGliderPAXLicence]                  BIT              CONSTRAINT [DF__Persons__HasGlid__52593CB8] DEFAULT ((0)) NOT NULL,
    [HasTMGLicence]                        BIT              CONSTRAINT [DF__Persons__HasTMGL__534D60F1] DEFAULT ((0)) NOT NULL,
    [HasWinchOperatorLicence]              BIT              CONSTRAINT [DF__Persons__HasWinc__5441852A] DEFAULT ((0)) NOT NULL,
    [SpotLink]                             NVARCHAR (250)   NULL,
    [IsFastEntryRecord]                    BIT              CONSTRAINT [DF__Persons__IsFastE__5535A963] DEFAULT ((1)) NOT NULL,
    [CreatedOn]                            DATETIME2 (7)    NOT NULL,
    [CreatedByUserId]                      UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]                           DATETIME2 (7)    NULL,
    [ModifiedByUserId]                     UNIQUEIDENTIFIER NULL,
    [DeletedOn]                            DATETIME2 (7)    NULL,
    [DeletedByUserId]                      UNIQUEIDENTIFIER NULL,
    [RecordState]                          INT              NULL,
    [OwnerId]                              UNIQUEIDENTIFIER NOT NULL,
    [OwnershipType]                        INT              NOT NULL,
    [IsDeleted]                            BIT              CONSTRAINT [DF__Persons__IsDelet__5629CD9C] DEFAULT ((0)) NOT NULL,
    [ReceiveOwnedAircraftStatisticReports] BIT              DEFAULT ((1)) NOT NULL,
    [MedicalClass1ExpireDate]              DATETIME2 (7)    NULL,
    [MedicalClass2ExpireDate]              DATETIME2 (7)    NULL,
    [MedicalLaplExpireDate]                DATETIME2 (7)    NULL,
    [HasGliderTowingStartPermission]       BIT              DEFAULT ((0)) NOT NULL,
    [HasGliderSelfStartPermission]         BIT              DEFAULT ((0)) NOT NULL,
    [HasGliderWinchStartPermission]        BIT              DEFAULT ((0)) NOT NULL,
    [LicenceNumber]                        NVARCHAR (20)    NULL,
    [GliderInstructorLicenceExpireDate]    DATETIME2 (7)    NULL,
    CONSTRAINT [PK_Persones] PRIMARY KEY CLUSTERED ([PersonId] ASC),
    CONSTRAINT [FK_Persons_Countries] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([CountryId])
);

