CREATE TABLE [dbo].[Users] (
    [UserId]                       UNIQUEIDENTIFIER NOT NULL,
    [ClubId]                       UNIQUEIDENTIFIER NOT NULL,
    [Username]                     NVARCHAR (256)   NOT NULL,
    [FriendlyName]                 NVARCHAR (100)   NOT NULL,
    [NotificationEmail]            NVARCHAR (256)   NOT NULL,
    [EmailConfirmed]               BIT              DEFAULT ((0)) NOT NULL,
    [PasswordHash]                 NVARCHAR (MAX)   NULL,
    [SecurityStamp]                NVARCHAR (MAX)   NULL,
    [PersonId]                     UNIQUEIDENTIFIER NULL,
    [Remarks]                      NVARCHAR (MAX)   NULL,
    [AccountState]                 INT              NOT NULL,
    [LastPasswordChangeOn]         DATETIME2 (7)    NULL,
    [ForcePasswordChangeNextLogon] BIT              DEFAULT ((0)) NOT NULL,
    [PhoneNumber]                  NVARCHAR (30)    NULL,
    [PhoneNumberConfirmed]         BIT              DEFAULT ((0)) NOT NULL,
    [TwoFactorEnabled]             BIT              DEFAULT ((0)) NOT NULL,
    [LockoutEnabled]               BIT              DEFAULT ((1)) NOT NULL,
    [LockoutEndDateUtc]            DATETIME2 (7)    NULL,
    [AccessFailedCount]            INT              DEFAULT ((0)) NOT NULL,
    [CreatedOn]                    DATETIME2 (7)    NOT NULL,
    [CreatedByUserId]              UNIQUEIDENTIFIER NOT NULL,
    [ModifiedOn]                   DATETIME2 (7)    NULL,
    [ModifiedByUserId]             UNIQUEIDENTIFIER NULL,
    [DeletedOn]                    DATETIME2 (7)    NULL,
    [DeletedByUserId]              UNIQUEIDENTIFIER NULL,
    [RecordState]                  INT              NULL,
    [OwnerId]                      UNIQUEIDENTIFIER NOT NULL,
    [OwnershipType]                INT              NOT NULL,
    [IsDeleted]                    BIT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserId] ASC),
    CONSTRAINT [FK_Users_Club] FOREIGN KEY ([ClubId]) REFERENCES [dbo].[Clubs] ([ClubId]),
    CONSTRAINT [FK_Users_Persons] FOREIGN KEY ([PersonId]) REFERENCES [dbo].[Persons] ([PersonId]),
    CONSTRAINT [FK_Users_UserAccountStates] FOREIGN KEY ([AccountState]) REFERENCES [dbo].[UserAccountStates] ([UserAccountStateId]),
    CONSTRAINT [UNIQUE_Users_Username] UNIQUE NONCLUSTERED ([Username] ASC, [DeletedOn] ASC)
);

