//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLS.Server.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FLS.Server.Data.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aircraft.
        /// </summary>
        public static string Aircraft {
            get {
                return ResourceManager.GetString("Aircraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AircraftAircraftStates.
        /// </summary>
        public static string AircraftAircraftStates {
            get {
                return ResourceManager.GetString("AircraftAircraftStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AircraftAircraftStates.AircraftStateRelation.
        /// </summary>
        public static string AircraftAircraftStatesAircraftStateRelation {
            get {
                return ResourceManager.GetString("AircraftAircraftStatesAircraftStateRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AircraftId.
        /// </summary>
        public static string AircraftId {
            get {
                return ResourceManager.GetString("AircraftId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AircraftState.
        /// </summary>
        public static string AircraftState {
            get {
                return ResourceManager.GetString("AircraftState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanHaveTwoPilots.
        /// </summary>
        public static string CanHaveTwoPilots {
            get {
                return ResourceManager.GetString("CanHaveTwoPilots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanLand.
        /// </summary>
        public static string CanLand {
            get {
                return ResourceManager.GetString("CanLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CanStart.
        /// </summary>
        public static string CanStart {
            get {
                return ResourceManager.GetString("CanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Club.
        /// </summary>
        public static string Club {
            get {
                return ResourceManager.GetString("Club", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClubId.
        /// </summary>
        public static string ClubId {
            get {
                return ResourceManager.GetString("ClubId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubname.
        /// </summary>
        public static string Clubname {
            get {
                return ResourceManager.GetString("Clubname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryId.
        /// </summary>
        public static string CountryId {
            get {
                return ResourceManager.GetString("CountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountryNotSetOrInvalid.
        /// </summary>
        public static string CountryNotSetOrInvalid {
            get {
                return ResourceManager.GetString("CountryNotSetOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultGliderFlightType.
        /// </summary>
        public static string DefaultGliderFlightType {
            get {
                return ResourceManager.GetString("DefaultGliderFlightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        public static string DefaultPassword {
            get {
                return ResourceManager.GetString("DefaultPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSendFailed.
        /// </summary>
        public static string EmailSendFailed {
            get {
                return ResourceManager.GetString("EmailSendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightCrews.
        /// </summary>
        public static string FlightCrews {
            get {
                return ResourceManager.GetString("FlightCrews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightCrews.Person.
        /// </summary>
        public static string FlightCrewsPerson {
            get {
                return ResourceManager.GetString("FlightCrewsPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightStatus.
        /// </summary>
        public static string FlightStatus {
            get {
                return ResourceManager.GetString("FlightStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightType.
        /// </summary>
        public static string FlightType {
            get {
                return ResourceManager.GetString("FlightType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightTypeId.
        /// </summary>
        public static string FlightTypeId {
            get {
                return ResourceManager.GetString("FlightTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightType.InstructorRequired.
        /// </summary>
        public static string FlightTypeInstructorRequired {
            get {
                return ResourceManager.GetString("FlightTypeInstructorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightType.IsPassengerFlight.
        /// </summary>
        public static string FlightTypeIsPassengerFlight {
            get {
                return ResourceManager.GetString("FlightTypeIsPassengerFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlightTypes.
        /// </summary>
        public static string FlightTypes {
            get {
                return ResourceManager.GetString("FlightTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5.
        /// </summary>
        public static string HashMethodMD5 {
            get {
                return ResourceManager.GetString("HashMethodMD5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLanded.
        /// </summary>
        public static string IsLanded {
            get {
                return ResourceManager.GetString("IsLanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdgDate.
        /// </summary>
        public static string LdgDate {
            get {
                return ResourceManager.GetString("LdgDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdgDateTime.
        /// </summary>
        public static string LdgDateTime {
            get {
                return ResourceManager.GetString("LdgDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdgLocation.
        /// </summary>
        public static string LdgLocation {
            get {
                return ResourceManager.GetString("LdgLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationId.
        /// </summary>
        public static string LocationId {
            get {
                return ResourceManager.GetString("LocationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flugplatz / Standort.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationType.
        /// </summary>
        public static string LocationType {
            get {
                return ResourceManager.GetString("LocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTypeId.
        /// </summary>
        public static string LocationTypeId {
            get {
                return ResourceManager.GetString("LocationTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationTypeNotSetOrInvalid.
        /// </summary>
        public static string LocationTypeNotSetOrInvalid {
            get {
                return ResourceManager.GetString("LocationTypeNotSetOrInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Flights could&apos;nt be updated..
        /// </summary>
        public static string LockedFlightCantBeUpdatedExceptionMessage {
            get {
                return ResourceManager.GetString("LockedFlightCantBeUpdatedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberStates.
        /// </summary>
        public static string MemberStates {
            get {
                return ResourceManager.GetString("MemberStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberOfFieldsWrong.
        /// </summary>
        public static string NumberOfFieldsWrong {
            get {
                return ResourceManager.GetString("NumberOfFieldsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonCategories.
        /// </summary>
        public static string PersonCategories {
            get {
                return ResourceManager.GetString("PersonCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonCategoryId.
        /// </summary>
        public static string PersonCategoryId {
            get {
                return ResourceManager.GetString("PersonCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonClubs.
        /// </summary>
        public static string PersonClubs {
            get {
                return ResourceManager.GetString("PersonClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonClubs.Club.
        /// </summary>
        public static string PersonClubsClub {
            get {
                return ResourceManager.GetString("PersonClubsClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonMemberStates.
        /// </summary>
        public static string PersonMemberStates {
            get {
                return ResourceManager.GetString("PersonMemberStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonPersonCategories.
        /// </summary>
        public static string PersonPersonCategories {
            get {
                return ResourceManager.GetString("PersonPersonCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SameEntityAlreadyExists.
        /// </summary>
        public static string SameEntityAlreadyExists {
            get {
                return ResourceManager.GetString("SameEntityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDate.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartDateTime.
        /// </summary>
        public static string StartDateTime {
            get {
                return ResourceManager.GetString("StartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartLocation.
        /// </summary>
        public static string StartLocation {
            get {
                return ResourceManager.GetString("StartLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartType.
        /// </summary>
        public static string StartType {
            get {
                return ResourceManager.GetString("StartType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTypeRelation.
        /// </summary>
        public static string StartTypeRelation {
            get {
                return ResourceManager.GetString("StartTypeRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TowFlight.
        /// </summary>
        public static string TowFlight {
            get {
                return ResourceManager.GetString("TowFlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRoles.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRoles.Role.
        /// </summary>
        public static string UserRolesRole {
            get {
                return ResourceManager.GetString("UserRolesRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRoles.Role.Permissions.
        /// </summary>
        public static string UserRolesRolePermissions {
            get {
                return ResourceManager.GetString("UserRolesRolePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
